### ISSUE TITLE
Get Webots working with ROS in a container

### ISSUE THREAD

**Issue by AlexBethel** [shastro/NMTLunabotics2023#1]
We need to get Webots (a robotics simulator; https://www.cyberbotics.com/) working inside of a Docker container, and we need it talking to ROS (almost certainly should be in another container). This should be done using Docker Compose.

**Comment by shastro** [comment]
Closed by #[217bab2]
(https://github.com/shastro/NMTLunabotics2023/commit/217bab20b1e6cfa3f4961af818bc3e527f4146b3)
