### ISSUE TITLE
Figure out how Docker is going to talk to CAN

### ISSUE THREAD

**Issue by AlexBethel** [shastro/NMTLunabotics2023#21]
Docker can only talk to (V)CAN if we allow `--network=host`; but if we allow `--network=host` on a container it's going to be difficult to get it to talk to the rest of the ROS network because none of Docker's DNS or anything will work.

**Comment by shastro** [comment]
@AlexBethel Is this resolved?

**Comment by AlexBethel** [comment]
Resolved by removing Docker Compose from the robot deployment workflow, and instead using a single container that is initialized by a shell script.
