### ISSUE TITLE
Pitch Motor Telemetry

### ISSUE THREAD

**Issue by dev-dwarf** [shastro/NMTLunabotics2023#25]
Need to fix telemetry on pitch motors.

We do not have enough pins that can use interrupts (we think).

According to docs only pins 0-3 and 7 can be used for interrupts.
0-1 seem to be used for can/serial comms, so its hard to use them for other things.
2-3 we are using to run the motor drivers using I2C.
7 we can't physically find, also we probably need 2 interrupt pins (1 for each motor).

options:
1. Read motor current using i2c, figure out experimentally how much it moves for a current amount.
2. Go back to a different mode (mode 9)? This would free up pins 2-3.
3. Use bigger arduino (more pins), manually add a can controller, communicate with it over i2c (might have to order this).

**Comment by shastro** [comment]
Done and outdated
